CREATE TABLE INDO_CMS_ROLE (
ROW_ID SERIAL NOT NULL,
ROLE_ID VARCHAR(100),
ROLENAME VARCHAR(100),
ROLEDESCRIPTION VARCHAR(100)
);

CREATE TABLE INDO_CMS_MENU (
ROW_ID SERIAL NOT NULL,
MENU_ID VARCHAR(100),
MENU_PARENT_ID VARCHAR(100),
MENU_TITLE VARCHAR(100),
MENU_SUBTITLE VARCHAR(100),
MENU_BREADCRUMB VARCHAR(200),
MENU_URL_TITLE VARCHAR(200),
MENU_URL VARCHAR(200),
MENU_SEQUENCE INTEGER
);

CREATE TABLE INDO_CMS_MENU_PERMISSION (
ROW_ID SERIAL NOT NULL,
MENU_ID VARCHAR(100),
ROLE_ID VARCHAR(100),
CAN_INSERT VARCHAR(1),
CAN_UPDATE VARCHAR(1),
CAN_DELETE VARCHAR(1),
CAN_EXPORT VARCHAR(1),
CAN_IMPORT VARCHAR(1)
);

CREATE TABLE INDO_CMS_MENU_PERMISSION (
ROW_ID SERIAL NOT NULL,
MENU_ID VARCHAR(100),
ROLE_ID VARCHAR(100),
CAN_INSERT VARCHAR(1),
CAN_UPDATE VARCHAR(1),
CAN_DELETE VARCHAR(1),
CAN_EXPORT VARCHAR(1),
CAN_IMPORT VARCHAR(1)
);

CREATE TABLE INDO_CMS_BANK (
ROW_ID SERIAL NOT NULL,
BANK_CODE VARCHAR(100),
BANK_NAME VARCHAR(100),
BANK_ADDRESS TEXT
);

CREATE TABLE INDO_CMS_BANK_CUSTOMER (
ROW_ID SERIAL NOT NULL,
BANK_CODE VARCHAR(100),
CUSTOMER_CODE VARCHAR(100),
CUSTOMER_NAME VARCHAR(100),
CUSTOMER_EMAIL VARCHAR(100),
CUSTOMER_GENDER VARCHAR(1),
CUSTOMER_ADDRESS TEXT
);

CREATE TABLE INDO_CMS_BANK_TRANSACTION (
ROW_ID SERIAL NOT NULL,
BANK_CODE VARCHAR(100),
CUSTOMER_CODE VARCHAR(100),
TRANSACTION_TYPE VARCHAR(100),
TRANSACTION_VALUE INTEGER,
TRANSACTION_OPEN_DATE DATE,
TRANSACTION_MAT_DATE DATE
);
