CREATE TABLE INDO_CMS_DOCUMENT (
ROW_ID SERIAL NOT NULL,
DOCUMENT_NAME VARCHAR(100),
DOCUMENT_DESCRIPTION TEXT,
DOCUMENT_EXT_TYPE VARCHAR(100),
DOCUMENT_SIZE VARCHAR(100),
DOCUMENT_PATH PATH,
DOCUMENT_CREATED_BY VARCHAR(100),
DOCUMENT_CREATED_DATE TIMESTAMP,
DOCUMENT_MODIFIED_BY VARCHAR(100),
DOCUMENT_MODIFIED_DATE TIMESTAMP
);
